name: lociPARSE
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy-base=1.26.3
  - tqdm=4.66.1
  - pytorch=2.2.0=py3.11_cuda12.1_cudnn8_0
  - torchvision
  - pip
